version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - SERVER_NAME=elasticsearch
      - discovery.type=single-node
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.1
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/log/mbsd_log:/var/log
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    ports:
      - "5601:5601"
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - I18N_LOCALE="ja-JP"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
    driver: local
